### ISSUE TITLE
Optimism support

### ISSUE THREAD

**Issue by elhaix** [joshstevens19/simple-uniswap-sdk#30]
Can you please add support for the L2 Optimism network?

**Comment by elhaix** [comment]
Re: []( https://community.optimism.io/docs/infra/networks.html)

To add this, simply adding ChainID = 10 for mainnet and ChainID=69 for Kovan testnet to the ChainID enum would do?

**Comment by joshstevens19** [comment]
It’s a bit more then that need to map the contract addresses .. will get to sorting this request a bit snowed over! Thanks for raising it

**Comment by elhaix** [comment]
This is great to hear, thank you. I was afraid the project was going dormant. 👍

**Comment by joshstevens19** [comment]
No no it’s well supported just been a busy month. Will get back on it in Jan!

**Comment by joshstevens19** [comment]
custom network handles this now
