### ISSUE TITLE
Polygon Main/Mumbai Contracts

### ISSUE THREAD

**Issue by LarryRyan0824** [joshstevens19/simple-uniswap-sdk#34]
Edit: I went with Uniswap instead of Sushi. 

I am having a hard time finding the **SushiSwap Router, Factory and Multicall** contract addresses for these chains. I got all the other chains to work. Anyone have any luck?

Here are the addresses I have tried, mixed together in different ways

**MultiCall**
0xef0881ec094552b2e128cf945ef17a6752b4ec5d
0xc2edad668740f1aa35e4d8f227fb8e17dca888cd

**Router**
0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F
0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506

**Factory/Pair**
0xf1c9881Be22EBF108B8927c4d197d126346b5036
0xc35DADB65012eC5796536bD9864eD8773aBc74C4

Here are the other contracts that work, I am sure they will help someone.

**BSC Main PancakeSwap**
`{
multicallContractAddress: '0x65e9a150e06c84003d15ae6a060fc2b1b393342c',
                cloneUniswapContractDetails: {
                    v2Override: {
                        routerAddress: '0x10ED43C718714eb63d5aA57B78B54704E256024E',
                        factoryAddress: '0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73',
                        pairAddress: '0xca143ce32fe78f1f7019d7d551a6402fc5350c73'
                    }
                }
}`

**BSC Testnet PancakeSwap**
`{
multicallContractAddress: '0x8F3273Fb89B075b1645095ABaC6ed17B2d4Bc576',
                cloneUniswapContractDetails: {
                    v2Override: {
                        routerAddress: '0xD99D1c33F9fC3444f8101754aBC46c52416550D1',
                        factoryAddress: '0x6725F303b657a9451d8BA641348b6761A6CC7a17',
                        pairAddress: '0x6725F303b657a9451d8BA641348b6761A6CC7a17'
                    }
                }
}`

**Pulse Chain Testnet Uniswap**
`{
multicallContractAddress: '0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696',
                cloneUniswapContractDetails: {
                    v2Override: {
                        routerAddress: '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D',
                        factoryAddress: '0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95',
                        pairAddress: '0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95'
                    }
                }
}`

**Comment by joshstevens19** [comment]
hey custom network should have this resolved right? closing can reopen if this is still an issue
