### ISSUE TITLE
Can't use with vite

### ISSUE THREAD

**Issue by hamicodes** [joshstevens19/simple-uniswap-sdk#37]
In a vue + ts + vite setup, importing this module gives the following error:

> Module "stream" has been externalized for browser compatibility and cannot be accessed in client code.

**Comment by joshstevens19** [comment]
you will need to use webpack to bundle it to turn it into browser code, also if you google your error you find a few answers!

out of scope for the project to bundle this in a way for you.. that's down to the app using it (angular, vue, react do this for you automatically so I'm guessing it is a simple thing to handle when using vite)

let me know if you get it to work
