### ISSUE TITLE
feat: AVALANCHE support 

### ISSUE THREAD

**Issue by mburger81** [joshstevens19/simple-uniswap-sdk#46]
Hello,

can you help on configuring the UniswapPair for Avalanche Main- and Testnet?

Can you maybe share an example?

@joshstevens19 
@vm06007

**Comment by vm06007** [comment]
you'll need to deploy `multicall` contract or use the one available on that chain first, do you know the address?

**Comment by mburger81** [comment]
maybe here?

https://github.com/makerdao/multicall/pull/32

**Comment by vm06007** [comment]
I've checked the router you're using (https://snowtrace.io/address/0x60ae616a2155ee3d9a68541ba4544862310933d4#code) it does not look like standard implementation of Uniswap contract code, in fact it has some token wrapper and some functions have different names such as `swapExactAVAXForTokens` and `swapTokensForExactAVAX` that means it won't work with this SDK, this SDK only works with standard implementations so it expects `swapExactETHForTokens` and `swapTokensForExactETH` if contract uses different ABI these functions won't be found and thus most certainly lead to an error.

**Comment by liu-zhipeng** [comment]
> I've checked the router you're using (https://snowtrace.io/address/0x60ae616a2155ee3d9a68541ba4544862310933d4#code) it does not look like standard implementation of Uniswap contract code, in fact it has some token wrapper and some functions have different names such as `swapExactAVAXForTokens` and `swapTokensForExactAVAX` that means it won't work with this SDK, this SDK only works with standard implementations so it expects `swapExactETHForTokens` and `swapTokensForExactETH` if contract uses different ABI these functions won't be found and thus most certainly lead to an error.

Yep! Exactly. Trader Joe and Pangolin swap have a bit different swap methods and abi as well.
So to use the avalanche dex, we need customized ABI and method names.

#45 
I am trying to add some features to support customized ABI and method names, Uniswap V3 multihop as well in this PR.
Not confirmed by @joshstevens19  yet.

**Comment by liu-zhipeng** [comment]
`
new UniswapPairSettings({
          slippage: 0.005,
          deadlineMinutes: DEFAULT_DEADLINE_MINUTES,
          disableMultihops: false,
          uniswapVersions: [UniswapVersion.v2],
          cloneUniswapContractDetails: {
            v2Override: {
              routerAddress: "0x60aE616a2155Ee3d9A68541Ba4544862310933d4",
              factoryAddress: "0x9ad6c38be94206ca50bb0d90783181662f0cfa10",
              pairAddress: "0x9ad6c38be94206ca50bb0d90783181662f0cfa10",
              routerAbi: TraderJoeRouterABI,
              routerMethods: {
                swapETHForExactTokens: "swapAVAXForExactTokens",
                swapExactETHForTokens: "swapExactAVAXForTokens",
                swapExactETHForTokensSupportingFeeOnTransferTokens:
                  "swapExactAVAXForTokensSupportingFeeOnTransferTokens",
                swapExactTokensForETH: "swapExactTokensForAVAX",
                swapExactTokensForETHSupportingFeeOnTransferTokens:
                  "swapExactTokensForAVAXSupportingFeeOnTransferTokens",
                swapExactTokensForTokens: "swapExactTokensForTokens",
                swapExactTokensForTokensSupportingFeeOnTransferTokens:
                  "swapExactTokensForTokensSupportingFeeOnTransferTokens",
                swapTokensForExactETH: "swapTokensForExactAVAX",
                swapTokensForExactTokens: "swapTokensForExactTokens",
              },
            },
          },
          customNetwork: {
            nameNetwork: "Avalanche",
            multicallContractAddress: "0xed386Fe855C1EFf2f843B910923Dd8846E45C5A4",
            nativeCurrency: {
              name: "AVAX",
              symbol: "AVAX",
            },
            nativeWrappedTokenInfo: {
              chainId: 43114,
              contractAddress: "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7",
              decimals: 18,
              symbol: "WAVAX",
              name: "Wrapped AVAX",
            },
            baseTokens: {
              usdt: {
                chainId: 43114,
                contractAddress: "0xc7198437980c041c805A1EDcbA50c1Ce5db95118",
                decimals: 6,
                symbol: "USDT",
                name: "USDT",
              },
              usdc: {
                chainId: 43114,
                contractAddress: "0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664",
                decimals: 6,
                symbol: "USDC.e",
                name: "USDC.e",
              },
              wbtc: {
                chainId: 43114,
                contractAddress: "0x152b9d0fdc40c096757f570a51e494bd4b943e50",
                decimals: 8,
                symbol: "BTC.b",
                name: "BTC.b",
              },
            },
          },
        }),
`

**Comment by vm06007** [comment]
cool

**Comment by liu-zhipeng** [comment]
> cool

@vm06007  if you have a chance, could you review my changes? 
#45

**Comment by joshstevens19** [comment]
Defo more eyes and a review from @vm06007 would be great as he knows how how v2 works as well! The main thing is breaking changes to the return interface which is the problem!
