### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by Vasile-Peste** [joshstevens19/simple-uniswap-sdk#49]
Hello, I can see from the repository root that the license is MIT, but from package.json and NPM license is indicated as ISC.
https://github.com/joshstevens19/simple-uniswap-sdk/blob/master/package.json#L30

May I know which one is the correct license? I'm planing to integrate this library into [Mida](https://github.com/Reiryoku-Technologies/Mida), thank you!

**Comment by joshstevens19** [comment]
Oops it’s MIT.. feel free to do a PR fixing it in the package.json this lib can be used by anyone freely

**Comment by joshstevens19** [comment]
Thanks for raising if you don’t do the PR will do it myself when next on computer

**Comment by joshstevens19** [comment]
Also excited to see it being used on Mida let me know how integration goes
