### ISSUE TITLE
Invalid from or to contract tokens

### ISSUE THREAD

**Issue by YauhenPachankou** [joshstevens19/simple-uniswap-sdk#57]
Hi!

I get this error when I make a new UniswapPair and run createFactory on Arbitrum Goerli (chainId === 421613). I have added multicallContractAddress and cloneUniswapContractDetails, but it still doesn't work. And can i skip nativeCurrency and nativeWrappedTokenInfo ?

So, maybe you can see what the problem is ? Thanks !

![Screenshot 2023-07-25 at 11 05 10](https://github.com/joshstevens19/simple-uniswap-sdk/assets/40360289/5cff92d3-5f44-4238-8c3a-70c6a3bb9d7a)

**Comment by savasadar** [comment]
Hello @YauhenPachankou,

How did you solve this problem?
